name: CI

on:
  push:
  pull_request:

jobs:
  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest
        uses: home-assistant/actions/hassfest@main

  tests:
    name: Tests and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Ruff Lint
        run: ruff check .
      - name: Pytest
        run: pytest -q --cov=custom_components --cov-report=term-missing
